## Basic setup
project: trial
inputDIR: .
outputDIR: ./results
metadata: ./metadata.tsv

## Alpha diversity measures plotting
target: disease_stat
target_groups: # Groups in target attribute
  - normal
  - adenoma
  - carcinoma
colors:  # color for target groups
  - green
  - blue
  - red
alpha-measures: #Alpha measures to plot
  - Shannon
  - Chao1
  - Simpson
  - InvSimpson
top-n: 5 # Number of genus, family or phylum to extract based on their abundance

## Differential abundance testing config
rank: Genus
minimum: 10 # for pruning purposes
formula: ~disease_stat
reference: normal # this group is used as a reference to compare with 