## Script to perform differential abundance testing
# Author: Pankaj Chejara
# Email: pankaj.chejara@metrosert.ee
# Last modified: 4th March 2025

# Import packages
library(ggplot2)
library('argparse')

library(readr)  # For read_csv

# Parsing command line arguments
parser <- ArgumentParser(description= 'This script plots DESeq2 analysis results.')

parser$add_argument('--deseq2Files', '-f', help= 'These are the files generated by deseq2 rule', nargs='+')
parser$add_argument('--ref', '-r', help= 'This is the reference group e.g., healthy')
parser$add_argument('--target', '-t', nargs='+', help= 'These are all target groups', required=TRUE)
parser$add_argument('--outputDir', '-o', help= 'Directory to store results')
parser$add_argument('--taxonomy', '-x', help= 'Taxonomic information for each feature')

# Parsing args
xargs <- parser$parse_args()

# Reference group
ref <- xargs$ref

# Groups to compare with
target_groups <- xargs$target
compare_groups <- target_groups[target_groups != ref]

# Output directory
output <- xargs$outputDir

# Taxonomy file
taxa_file <- xargs$taxonomy

# Files containing DESeq2 results for each group
files <- xargs$deseq2Files

for (file in files) {
    # Read DESeq2 results
    df <- read_csv(file,show_col_types = FALSE)
    print(file)
    # Get file name without extension
    file_name <- tools::file_path_sans_ext(basename(file))

    # Extract groups from file name
    groups <- unlist(strsplit(file_name, '-'))

    #plot_file <- paste0(output, '/', file_name, '.pdf')
    plot_file_png <- paste0(output, '/plot/', file_name, '.png')

    group1 <- groups[2]
    group2 <- groups[3]

    # Read taxonomy file
    taxa <- read_csv(taxa_file)

    # Merging DESeq2 results and taxonomic info
    merged_df <- merge(df, taxa, by.x = colnames(df)[1],by.y=colnames(taxa)[1], all = FALSE)  

    # Remove records having NA for p-adjusted values
    df_cleaned <- merged_df[!is.na(merged_df$padj), ]

    # Removing records with adjusted p-value < 0.05
    df_filtered <- df_cleaned[df_cleaned$padj <= 0.05, ]

    # Sort on log2 fold change
    df_sorted <- df_filtered[order(df_filtered$log2FoldChange, decreasing = TRUE), ]

    # Create a new column for coloring based on log2FoldChange (green for positive, red for negative)
    df_sorted$color <- ifelse(df_sorted$log2FoldChange > 0, "green", "red")

    # Create the plot
    plot <- ggplot(df_sorted, aes(x=reorder(Genus, log2FoldChange), y=log2FoldChange,fill=color)) + 
            geom_bar(stat='identity') + 
            scale_fill_manual(values = c("green" = "forestgreen", "red" = "firebrick3")) +
            coord_flip() +
            ggtitle(paste("Differential Abundance -", group1, "vs", group2)) +
            theme(legend.position='none')

    #ggsave(plot_file,plot,device='pdf')
    ggsave(plot_file_png,plot,device='png')
}
