## Script to perform differential abundance testing
# Author: Pankaj Chejara
# Email: pankaj.chejara@metrosert.ee
# Last modified: 4th March 2025

# Import packages
library(ggplot2)
library('argparse')

library(readr)  # For read_csv

# Parsing command line arguments
parser <- ArgumentParser(description= 'This script plots DESeq2 analysis results.')
parser$add_argument('--taxaLevel', '-t', help= 'Taxa level at which wilcoxon test was performed')
parser$add_argument('--wilcoxonFiles', '-f', help= 'These are the files generated by wilcoxon rule', nargs='+')
parser$add_argument('--outputDir', '-o', help= 'Directory to store results')

# Parsing args
xargs <- parser$parse_args()

# Taxa level
taxa <- xargs$taxaLevel

# Output directory
output <- xargs$outputDir

# Files containing Wilcoxon results for each group
files <- xargs$wilcoxonFiles

for (file in files) {
    # Read Wilcoxon results
    df <- read_csv(file,show_col_types = FALSE)

    # Get file name without extension
    file_name <- tools::file_path_sans_ext(basename(file))

    # Extract groups from file name
    groups <- unlist(strsplit(file_name, '-'))

    plot_file <- paste0(output, '/', file_name, '.pdf')

    group1 <- groups[2]
    group2 <- groups[3]


    # Extract records with adjusted p-value < 0.05
    sig_df <- df %>%
              filter(P_adjusted < 0.05 & !is.na(P_adjusted)) %>%
              select(Taxon, P_value, P_adjusted)

    


    # Create the plot
    plot <- ggplot(df_filtered, aes(x=taxa, y=log2FoldChange,fill=color)) + 
            geom_bar(stat='identity') + 
            scale_fill_manual(values = c("green" = "green", "red" = "red")) +
            coord_flip() +
            ggtitle(paste("Differential Abundance -", group1, "vs", group2)) +
            theme(legend.position='none')

    ggsave(plot_file,plot,device='pdf')
}
